export { default as Navbar } from "./Navbar";
export { default as Main } from "./Main";
export { default as Header } from "./Header";
export { default as TrendingContent } from "./TrendingContent";
export { default as MediaCard } from "./MediaCard";
export { default as PrimaryBtn } from "./PrimaryBtn";
export { default as SecondaryBtn } from "./SecondaryBtn";
export { default as Home } from "./pages/Home";
export { default as Details } from "./pages/Details";
