export const logo = "/assets/logo.png";
export const backdrop = "/assets/pushpa_backdrop.png";
export const imageBaseUrl = "https://image.tmdb.org/t/p/";
// embed youtube base url
export const youtubeBaseUrl = "https://www.youtube.com/embed/";
// ids for genres used in api
export const genres = [
  {
    id: 28,
    name: "Action",
  },
  {
    id: 12,
    name: "Adventure",
  },
  {
    id: 16,
    name: "Animation",
  },
  {
    id: 35,
    name: "Comedy",
  },
  {
    id: 80,
    name: "Crime",
  },
  {
    id: 99,
    name: "Documentary",
  },
  {
    id: 18,
    name: "Drama",
  },
  {
    id: 10751,
    name: "Family",
  },
  {
    id: 14,
    name: "Fantasy",
  },
  {
    id: 36,
    name: "History",
  },
  {
    id: 27,
    name: "Horror",
  },
  {
    id: 10402,
    name: "Music",
  },
  {
    id: 9648,
    name: "Mystery",
  },
  {
    id: 10749,
    name: "Romance",
  },
  {
    id: 878,
    name: "Science Fiction",
  },
  {
    id: 10770,
    name: "TV Movie",
  },
  {
    id: 53,
    name: "Thriller",
  },
  {
    id: 10752,
    name: "War",
  },
  {
    id: 37,
    name: "Western",
  },
];
// ids for languages used in api
export const languages = [
  {
    iso_639_1: "an",
    english_name: "Aragonese",
    name: "",
  },
  {
    iso_639_1: "ak",
    english_name: "Akan",
    name: "",
  },
  {
    iso_639_1: "cr",
    english_name: "Cree",
    name: "",
  },
  {
    iso_639_1: "az",
    english_name: "Azerbaijani",
    name: "Azərbaycan",
  },
  {
    iso_639_1: "cs",
    english_name: "Czech",
    name: "Český",
  },
  {
    iso_639_1: "aa",
    english_name: "Afar",
    name: "",
  },
  {
    iso_639_1: "br",
    english_name: "Breton",
    name: "",
  },
  {
    iso_639_1: "af",
    english_name: "Afrikaans",
    name: "Afrikaans",
  },
  {
    iso_639_1: "bo",
    english_name: "Tibetan",
    name: "",
  },
  {
    iso_639_1: "ce",
    english_name: "Chechen",
    name: "",
  },
  {
    iso_639_1: "kw",
    english_name: "Cornish",
    name: "",
  },
  {
    iso_639_1: "fo",
    english_name: "Faroese",
    name: "",
  },
  {
    iso_639_1: "la",
    english_name: "Latin",
    name: "Latin",
  },
  {
    iso_639_1: "ng",
    english_name: "Ndonga",
    name: "",
  },
  {
    iso_639_1: "sc",
    english_name: "Sardinian",
    name: "",
  },
  {
    iso_639_1: "ti",
    english_name: "Tigrinya",
    name: "",
  },
  {
    iso_639_1: "tn",
    english_name: "Tswana",
    name: "",
  },
  {
    iso_639_1: "tr",
    english_name: "Turkish",
    name: "Türkçe",
  },
  {
    iso_639_1: "pa",
    english_name: "Punjabi",
    name: "ਪੰਜਾਬੀ",
  },
  {
    iso_639_1: "et",
    english_name: "Estonian",
    name: "Eesti",
  },
  {
    iso_639_1: "fr",
    english_name: "French",
    name: "Français",
  },
  {
    iso_639_1: "ha",
    english_name: "Hausa",
    name: "Hausa",
  },
  {
    iso_639_1: "is",
    english_name: "Icelandic",
    name: "Íslenska",
  },
  {
    iso_639_1: "li",
    english_name: "Limburgish",
    name: "",
  },
  {
    iso_639_1: "ln",
    english_name: "Lingala",
    name: "",
  },
  {
    iso_639_1: "ss",
    english_name: "Swati",
    name: "",
  },
  {
    iso_639_1: "ab",
    english_name: "Abkhazian",
    name: "",
  },
  {
    iso_639_1: "sh",
    english_name: "Serbo-Croatian",
    name: "",
  },
  {
    iso_639_1: "eu",
    english_name: "Basque",
    name: "euskera",
  },
  {
    iso_639_1: "fy",
    english_name: "Frisian",
    name: "",
  },
  {
    iso_639_1: "ja",
    english_name: "Japanese",
    name: "日本語",
  },
  {
    iso_639_1: "oj",
    english_name: "Ojibwa",
    name: "",
  },
  {
    iso_639_1: "or",
    english_name: "Oriya",
    name: "",
  },
  {
    iso_639_1: "pi",
    english_name: "Pali",
    name: "",
  },
  {
    iso_639_1: "su",
    english_name: "Sundanese",
    name: "",
  },
  {
    iso_639_1: "th",
    english_name: "Thai",
    name: "ภาษาไทย",
  },
  {
    iso_639_1: "ig",
    english_name: "Igbo",
    name: "",
  },
  {
    iso_639_1: "id",
    english_name: "Indonesian",
    name: "Bahasa indonesia",
  },
  {
    iso_639_1: "kk",
    english_name: "Kazakh",
    name: "қазақ",
  },
  {
    iso_639_1: "ki",
    english_name: "Kikuyu",
    name: "",
  },
  {
    iso_639_1: "ug",
    english_name: "Uighur",
    name: "",
  },
  {
    iso_639_1: "ve",
    english_name: "Venda",
    name: "",
  },
  {
    iso_639_1: "rw",
    english_name: "Kinyarwanda",
    name: "Kinyarwanda",
  },
  {
    iso_639_1: "mi",
    english_name: "Maori",
    name: "",
  },
  {
    iso_639_1: "nv",
    english_name: "Navajo",
    name: "",
  },
  {
    iso_639_1: "hi",
    english_name: "Hindi",
    name: "हिन्दी",
  },
  {
    iso_639_1: "pt",
    english_name: "Portuguese",
    name: "Português",
  },
  {
    iso_639_1: "sg",
    english_name: "Sango",
    name: "",
  },
  {
    iso_639_1: "sk",
    english_name: "Slovak",
    name: "Slovenčina",
  },
  {
    iso_639_1: "sr",
    english_name: "Serbian",
    name: "Srpski",
  },
  {
    iso_639_1: "ty",
    english_name: "Tahitian",
    name: "",
  },
  {
    iso_639_1: "xh",
    english_name: "Xhosa",
    name: "",
  },
  {
    iso_639_1: "ar",
    english_name: "Arabic",
    name: "العربية",
  },
  {
    iso_639_1: "co",
    english_name: "Corsican",
    name: "",
  },
  {
    iso_639_1: "bi",
    english_name: "Bislama",
    name: "",
  },
  {
    iso_639_1: "eo",
    english_name: "Esperanto",
    name: "Esperanto",
  },
  {
    iso_639_1: "hz",
    english_name: "Herero",
    name: "",
  },
  {
    iso_639_1: "fi",
    english_name: "Finnish",
    name: "suomi",
  },
  {
    iso_639_1: "iu",
    english_name: "Inuktitut",
    name: "",
  },
  {
    iso_639_1: "lv",
    english_name: "Latvian",
    name: "Latviešu",
  },
  {
    iso_639_1: "it",
    english_name: "Italian",
    name: "Italiano",
  },
  {
    iso_639_1: "nl",
    english_name: "Dutch",
    name: "Nederlands",
  },
  {
    iso_639_1: "kn",
    english_name: "Kannada",
    name: "?????",
  },
  {
    iso_639_1: "sa",
    english_name: "Sanskrit",
    name: "",
  },
  {
    iso_639_1: "sq",
    english_name: "Albanian",
    name: "shqip",
  },
  {
    iso_639_1: "tl",
    english_name: "Tagalog",
    name: "",
  },
  {
    iso_639_1: "lb",
    english_name: "Letzeburgesch",
    name: "",
  },
  {
    iso_639_1: "ts",
    english_name: "Tsonga",
    name: "",
  },
  {
    iso_639_1: "ml",
    english_name: "Malayalam",
    name: "",
  },
  {
    iso_639_1: "vo",
    english_name: "Volapük",
    name: "",
  },
  {
    iso_639_1: "zu",
    english_name: "Zulu",
    name: "isiZulu",
  },
  {
    iso_639_1: "os",
    english_name: "Ossetian; Ossetic",
    name: "",
  },
  {
    iso_639_1: "sm",
    english_name: "Samoan",
    name: "",
  },
  {
    iso_639_1: "za",
    english_name: "Zhuang",
    name: "",
  },
  {
    iso_639_1: "bn",
    english_name: "Bengali",
    name: "বাংলা",
  },
  {
    iso_639_1: "cu",
    english_name: "Slavic",
    name: "",
  },
  {
    iso_639_1: "ga",
    english_name: "Irish",
    name: "Gaeilge",
  },
  {
    iso_639_1: "gv",
    english_name: "Manx",
    name: "",
  },
  {
    iso_639_1: "hu",
    english_name: "Hungarian",
    name: "Magyar",
  },
  {
    iso_639_1: "jv",
    english_name: "Javanese",
    name: "",
  },
  {
    iso_639_1: "kr",
    english_name: "Kanuri",
    name: "",
  },
  {
    iso_639_1: "km",
    english_name: "Khmer",
    name: "",
  },
  {
    iso_639_1: "ky",
    english_name: "Kirghiz",
    name: "??????",
  },
  {
    iso_639_1: "na",
    english_name: "Nauru",
    name: "",
  },
  {
    iso_639_1: "nr",
    english_name: "Ndebele",
    name: "",
  },
  {
    iso_639_1: "oc",
    english_name: "Occitan",
    name: "",
  },
  {
    iso_639_1: "ro",
    english_name: "Romanian",
    name: "Română",
  },
  {
    iso_639_1: "ru",
    english_name: "Russian",
    name: "Pусский",
  },
  {
    iso_639_1: "hy",
    english_name: "Armenian",
    name: "",
  },
  {
    iso_639_1: "ch",
    english_name: "Chamorro",
    name: "Finu' Chamorro",
  },
  {
    iso_639_1: "xx",
    english_name: "No Language",
    name: "No Language",
  },
  {
    iso_639_1: "ba",
    english_name: "Bashkir",
    name: "",
  },
  {
    iso_639_1: "gl",
    english_name: "Galician",
    name: "Galego",
  },
  {
    iso_639_1: "io",
    english_name: "Ido",
    name: "",
  },
  {
    iso_639_1: "lu",
    english_name: "Luba-Katanga",
    name: "",
  },
  {
    iso_639_1: "mh",
    english_name: "Marshall",
    name: "",
  },
  {
    iso_639_1: "mg",
    english_name: "Malagasy",
    name: "",
  },
  {
    iso_639_1: "mo",
    english_name: "Moldavian",
    name: "",
  },
  {
    iso_639_1: "mn",
    english_name: "Mongolian",
    name: "",
  },
  {
    iso_639_1: "nd",
    english_name: "Ndebele",
    name: "",
  },
  {
    iso_639_1: "no",
    english_name: "Norwegian",
    name: "Norsk",
  },
  {
    iso_639_1: "pl",
    english_name: "Polish",
    name: "Polski",
  },
  {
    iso_639_1: "sw",
    english_name: "Swahili",
    name: "Kiswahili",
  },
  {
    iso_639_1: "tg",
    english_name: "Tajik",
    name: "",
  },
  {
    iso_639_1: "to",
    english_name: "Tonga",
    name: "",
  },
  {
    iso_639_1: "wa",
    english_name: "Walloon",
    name: "",
  },
  {
    iso_639_1: "yi",
    english_name: "Yiddish",
    name: "",
  },
  {
    iso_639_1: "en",
    english_name: "English",
    name: "English",
  },
  {
    iso_639_1: "as",
    english_name: "Assamese",
    name: "",
  },
  {
    iso_639_1: "gd",
    english_name: "Gaelic",
    name: "",
  },
  {
    iso_639_1: "kl",
    english_name: "Kalaallisut",
    name: "",
  },
  {
    iso_639_1: "my",
    english_name: "Burmese",
    name: "",
  },
  {
    iso_639_1: "qu",
    english_name: "Quechua",
    name: "",
  },
  {
    iso_639_1: "sn",
    english_name: "Shona",
    name: "",
  },
  {
    iso_639_1: "uk",
    english_name: "Ukrainian",
    name: "Український",
  },
  {
    iso_639_1: "fa",
    english_name: "Persian",
    name: "فارسی",
  },
  {
    iso_639_1: "ka",
    english_name: "Georgian",
    name: "ქართული",
  },
  {
    iso_639_1: "gu",
    english_name: "Gujarati",
    name: "",
  },
  {
    iso_639_1: "av",
    english_name: "Avaric",
    name: "",
  },
  {
    iso_639_1: "ae",
    english_name: "Avestan",
    name: "",
  },
  {
    iso_639_1: "gn",
    english_name: "Guarani",
    name: "",
  },
  {
    iso_639_1: "mt",
    english_name: "Maltese",
    name: "Malti",
  },
  {
    iso_639_1: "ne",
    english_name: "Nepali",
    name: "",
  },
  {
    iso_639_1: "sv",
    english_name: "Swedish",
    name: "svenska",
  },
  {
    iso_639_1: "tt",
    english_name: "Tatar",
    name: "",
  },
  {
    iso_639_1: "wo",
    english_name: "Wolof",
    name: "Wolof",
  },
  {
    iso_639_1: "cn",
    english_name: "Cantonese",
    name: "广州话 / 廣州話",
  },
  {
    iso_639_1: "cv",
    english_name: "Chuvash",
    name: "",
  },
  {
    iso_639_1: "da",
    english_name: "Danish",
    name: "Dansk",
  },
  {
    iso_639_1: "dz",
    english_name: "Dzongkha",
    name: "",
  },
  {
    iso_639_1: "ny",
    english_name: "Chichewa; Nyanja",
    name: "",
  },
  {
    iso_639_1: "rn",
    english_name: "Rundi",
    name: "Kirundi",
  },
  {
    iso_639_1: "st",
    english_name: "Sotho",
    name: "",
  },
  {
    iso_639_1: "tk",
    english_name: "Turkmen",
    name: "",
  },
  {
    iso_639_1: "uz",
    english_name: "Uzbek",
    name: "ozbek",
  },
  {
    iso_639_1: "vi",
    english_name: "Vietnamese",
    name: "Tiếng Việt",
  },
  {
    iso_639_1: "el",
    english_name: "Greek",
    name: "ελληνικά",
  },
  {
    iso_639_1: "ca",
    english_name: "Catalan",
    name: "Català",
  },
  {
    iso_639_1: "cy",
    english_name: "Welsh",
    name: "Cymraeg",
  },
  {
    iso_639_1: "de",
    english_name: "German",
    name: "Deutsch",
  },
  {
    iso_639_1: "ks",
    english_name: "Kashmiri",
    name: "",
  },
  {
    iso_639_1: "ms",
    english_name: "Malay",
    name: "Bahasa melayu",
  },
  {
    iso_639_1: "nb",
    english_name: "Norwegian Bokmål",
    name: "Bokmål",
  },
  {
    iso_639_1: "rm",
    english_name: "Raeto-Romance",
    name: "",
  },
  {
    iso_639_1: "si",
    english_name: "Sinhalese",
    name: "සිංහල",
  },
  {
    iso_639_1: "es",
    english_name: "Spanish",
    name: "Español",
  },
  {
    iso_639_1: "te",
    english_name: "Telugu",
    name: "తెలుగు",
  },
  {
    iso_639_1: "tw",
    english_name: "Twi",
    name: "",
  },
  {
    iso_639_1: "ps",
    english_name: "Pushto",
    name: "پښتو",
  },
  {
    iso_639_1: "bg",
    english_name: "Bulgarian",
    name: "български език",
  },
  {
    iso_639_1: "mk",
    english_name: "Macedonian",
    name: "",
  },
  {
    iso_639_1: "ik",
    english_name: "Inupiaq",
    name: "",
  },
  {
    iso_639_1: "ko",
    english_name: "Korean",
    name: "한국어/조선말",
  },
  {
    iso_639_1: "lt",
    english_name: "Lithuanian",
    name: "Lietuvių",
  },
  {
    iso_639_1: "om",
    english_name: "Oromo",
    name: "",
  },
  {
    iso_639_1: "se",
    english_name: "Northern Sami",
    name: "",
  },
  {
    iso_639_1: "so",
    english_name: "Somali",
    name: "Somali",
  },
  {
    iso_639_1: "ta",
    english_name: "Tamil",
    name: "தமிழ்",
  },
  {
    iso_639_1: "ur",
    english_name: "Urdu",
    name: "اردو",
  },
  {
    iso_639_1: "am",
    english_name: "Amharic",
    name: "",
  },
  {
    iso_639_1: "bs",
    english_name: "Bosnian",
    name: "Bosanski",
  },
  {
    iso_639_1: "dv",
    english_name: "Divehi",
    name: "",
  },
  {
    iso_639_1: "ay",
    english_name: "Aymara",
    name: "",
  },
  {
    iso_639_1: "bm",
    english_name: "Bambara",
    name: "Bamanankan",
  },
  {
    iso_639_1: "ii",
    english_name: "Yi",
    name: "",
  },
  {
    iso_639_1: "ie",
    english_name: "Interlingue",
    name: "",
  },
  {
    iso_639_1: "kv",
    english_name: "Komi",
    name: "",
  },
  {
    iso_639_1: "ku",
    english_name: "Kurdish",
    name: "",
  },
  {
    iso_639_1: "nn",
    english_name: "Norwegian Nynorsk",
    name: "",
  },
  {
    iso_639_1: "zh",
    english_name: "Mandarin",
    name: "普通话",
  },
  {
    iso_639_1: "he",
    english_name: "Hebrew",
    name: "עִבְרִית",
  },
  {
    iso_639_1: "ee",
    english_name: "Ewe",
    name: "Èʋegbe",
  },
  {
    iso_639_1: "fj",
    english_name: "Fijian",
    name: "",
  },
  {
    iso_639_1: "ff",
    english_name: "Fulah",
    name: "Fulfulde",
  },
  {
    iso_639_1: "ht",
    english_name: "Haitian; Haitian Creole",
    name: "",
  },
  {
    iso_639_1: "hr",
    english_name: "Croatian",
    name: "Hrvatski",
  },
  {
    iso_639_1: "ia",
    english_name: "Interlingua",
    name: "",
  },
  {
    iso_639_1: "kj",
    english_name: "Kuanyama",
    name: "",
  },
  {
    iso_639_1: "lo",
    english_name: "Lao",
    name: "",
  },
  {
    iso_639_1: "lg",
    english_name: "Ganda",
    name: "",
  },
  {
    iso_639_1: "mr",
    english_name: "Marathi",
    name: "",
  },
  {
    iso_639_1: "sd",
    english_name: "Sindhi",
    name: "",
  },
  {
    iso_639_1: "be",
    english_name: "Belarusian",
    name: "беларуская мова",
  },
  {
    iso_639_1: "ho",
    english_name: "Hiri Motu",
    name: "",
  },
  {
    iso_639_1: "kg",
    english_name: "Kongo",
    name: "",
  },
  {
    iso_639_1: "sl",
    english_name: "Slovenian",
    name: "Slovenščina",
  },
  {
    iso_639_1: "yo",
    english_name: "Yoruba",
    name: "Èdè Yorùbá",
  },
];
// DUMMY DATA
export const upcomingMovies = [
  {
    adult: false,
    backdrop_path: "/sJN04jAqCgiZ5mWjzD5WX49ncca.jpg",
    genre_ids: [28, 18, 53],
    id: 864692,
    original_language: "hi",
    original_title: "पठान",
    overview:
      "A soldier caught by enemies and presumed dead comes back to complete his mission, accompanied by old companions and foes.",
    popularity: 29.098,
    poster_path: "/m1b9toKYyCujHuLoXB5GSDunO9e.jpg",
    release_date: "2023-01-25",
    title: "Pathaan",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/6nS2PhKIsOkcVMZroH2diX3U27l.jpg",
    genre_ids: [53],
    id: 872028,
    original_language: "ml",
    original_title: "Alone",
    overview: "",
    popularity: 9.834,
    poster_path: "/1YoSk9SH4zW1piVORvHp0VLs4MM.jpg",
    release_date: "2023-01-26",
    title: "Alone",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/eBa978z4R19VXT1JSB9g5kk8T4k.jpg",
    genre_ids: [28, 53],
    id: 938890,
    original_language: "te",
    original_title: "Hunt",
    overview: "",
    popularity: 9.241,
    poster_path: "/6QnfT7zunSxKwbQmmT9FoxccwZe.jpg",
    release_date: "2023-01-26",
    title: "Hunt",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/glHgUMsme2couS42hBoPfvhwArC.jpg",
    genre_ids: [],
    id: 859664,
    original_language: "bn",
    original_title: "Footprints",
    overview:
      "A morning in the life of a house help comes crashing down on her as she navigates various odds at her home and at the place where she works.",
    popularity: 10.543,
    poster_path: "/zgTxHRXDbF6M0j7fjMR50On4nj7.jpg",
    release_date: "2023-01-22",
    title: "Footprints",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 1067209,
    original_language: "en",
    original_title: "Gandhi Godse Ek Yudh",
    overview:
      "The video depicts the war of ideologies between Mahatma Gandhi and Nathuram Godse, increasing the curiosity level amongst the viewers to watch the film.",
    popularity: 9.756,
    poster_path: "/7MKuFlrrLJtiV49sxL4P640KP6M.jpg",
    release_date: "2023-01-26",
    title: "Gandhi Godse Ek Yudh",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [28, 53],
    id: 942058,
    original_language: "hi",
    original_title: "Tehran",
    overview: "Upcoming hindi action-thriller",
    popularity: 9.422,
    poster_path: "/wM1kwZfiulxeBUCdeFoblNLTcgM.jpg",
    release_date: "2023-01-26",
    title: "Tehran",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 881935,
    original_language: "bn",
    original_title: "Doctor Bakshi",
    overview:
      "After serving a jail sentence, Doctor Bakshi resumes his methods of seeking justice.",
    popularity: 8.15,
    poster_path: "/vUvybeq2TZthXD6w8oRDwJ0sWln.jpg",
    release_date: "2023-01-27",
    title: "Doctor Bakshi",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/uonWHNSayYsAJTKAmFzZV2EYkq1.jpg",
    genre_ids: [18, 80],
    id: 797186,
    original_language: "ml",
    original_title: "തങ്കം",
    overview: "",
    popularity: 9.058,
    poster_path: "/lB4VhlVcJGxBTHtSgFaCJdFrmxL.jpg",
    release_date: "2023-01-26",
    title: "Thankam",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/buamYrukfn58GdKHF3kF7U2F0dq.jpg",
    genre_ids: [18, 10749],
    id: 1045394,
    original_language: "te",
    original_title: "బుట్టబొమ్మ",
    overview:
      "A young woman falls in love with a man after dialing his number by mistake. However, when she visits his city to meet him, another stranger enters her life.",
    popularity: 8.561,
    poster_path: "/7BkOzXTTwSO11AMTp9dO3tuLXOd.jpg",
    release_date: "2023-01-26",
    title: "Butta Bomma",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18],
    id: 1039062,
    original_language: "as",
    original_title: "Anur",
    overview: "",
    popularity: 6.185,
    poster_path: "/4bawk6pnHU6Ghn1OoDd7rape7aM.jpg",
    release_date: "2023-01-27",
    title: "Eyes on the Sunshine",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/vRqpsbtyoawRgo0hGVBbcfLXymB.jpg",
    genre_ids: [10749, 18, 10402],
    id: 1049623,
    original_language: "hi",
    original_title: "Almost Pyaar with DJ Mohabbat",
    overview:
      "In London, a girl likes a boy a little too much. And, in a parallel universe, there's a boy who likes a girl. These two unrequited love stories, burdened by social status, caste, religion and inequality are breathlessly headed towards each other...two tragic love stories, one musical and an uncanny coincidence as told by the Guru of Love: DJ Mohabbat.",
    popularity: 3.47,
    poster_path: "/5OKVJdLBFB2EOjCNpZlnu09HVL1.jpg",
    release_date: "2023-02-03",
    title: "Almost Pyaar with DJ Mohabbat",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/489kR2a6iZFx25FtRdpvVMPHaLv.jpg",
    genre_ids: [28, 53],
    id: 1019638,
    original_language: "hi",
    original_title: "Faraaz",
    overview:
      "Based on the real-life terrorist attack that ravaged a Dhaka cafe, Faraaz is a tense hostage drama that unspools over one claustrophobic night.",
    popularity: 4.899,
    poster_path: "/5Dn3X97sTB15sBIdX8gkkhqCOyD.jpg",
    release_date: "2023-02-03",
    title: "Faraaz",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/4aT9KMfA8Q5aKgL8LAu5PIcU3OF.jpg",
    genre_ids: [10751],
    id: 1075867,
    original_language: "ta",
    original_title: "Meippada Sei",
    overview:
      "Four ignorant boys were surviving their life with the support of parents in Tanjore village, one of them (Muthupandi) falling in love, thereby, opposition occurring, cause of lower & upper casting and racism, then how he got marry with his girlfriend moreover, to escaping from their parents, the couple has decided to moved towards Chennai along with friends of muthupandi, After arrival at Chennai before start-up of their life over there, unfortunately, they found the injured hand of the someone’s body in dead condition at the back side of their residence, scared and reported to the nearby police station, accordingly, they got assaulted by concerned local gangster. The Meippada Sei Climax would be illustrated: Whether the criminal has been punished by Indian law? Or Ignorant / village people? And how are they rejoining their families? The movie will be a family entertainer and contains the 4 fights & 4 songs, moreover with the message of sexual harassment/ abuse for society.",
    popularity: 5.379,
    poster_path: "/9QqfW5GQEx89MhbQcd8uWK88rp3.jpg",
    release_date: "2023-01-27",
    title: "Meippada Sei",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/xvjSATJp8xS1EKkmqWPTfU6KD9B.jpg",
    genre_ids: [],
    id: 945167,
    original_language: "ml",
    original_title: "ഇരട്ട",
    overview: "",
    popularity: 4.33,
    poster_path: "/ittBLkDQ0e605gHBpl73sFmRsmd.jpg",
    release_date: "2023-02-03",
    title: "Iratta",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/k4XRBh9WbNEStWs35Y3Egv29e0A.jpg",
    genre_ids: [35, 27],
    id: 976121,
    original_language: "ml",
    original_title: "രോമാഞ്ചം",
    overview:
      "Romancham is a story based on real incidents that happened in the life of 7 bachelors in Bangalore in 2007 after playing the Ouija board and events followed by it.",
    popularity: 3.533,
    poster_path: "/kQ4xbvyo5b2xjyvpIoLqTpVPP5J.jpg",
    release_date: "2023-02-03",
    title: "Romancham",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 953120,
    original_language: "ml",
    original_title: "ബൂമറാംഗ്",
    overview: "",
    popularity: 3.458,
    poster_path: "/ewg6pD4ov1Kz1Yi8oAP8svNVYMQ.jpg",
    release_date: "2023-02-03",
    title: "Boomerang",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/A8K7IIPiQykcZ3iNr4iE3oJNLc7.jpg",
    genre_ids: [28, 18],
    id: 866198,
    original_language: "ta",
    original_title: "மைக்கேல்",
    overview: "",
    popularity: 3.443,
    poster_path: "/1HChuuIpOungXAtotqVfhCBZUBK.jpg",
    release_date: "2023-02-03",
    title: "Michael",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 981372,
    original_language: "ml",
    original_title: "വെടിക്കെട്ടു",
    overview: "",
    popularity: 3.825,
    poster_path: null,
    release_date: "2023-02-03",
    title: "Vedikettu",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 881420,
    original_language: "ml",
    original_title: "Momo in Dubai",
    overview: "",
    popularity: 3.431,
    poster_path: "/uaj6jwRt7dowCLh2u1A4jbuwVEZ.jpg",
    release_date: "2023-02-03",
    title: "Momo in Dubai",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/7fIRDNUxrn6ulDXYWEgzmw0O9JB.jpg",
    genre_ids: [28, 35, 18, 10749],
    id: 884434,
    original_language: "hi",
    original_title: "Shehzada",
    overview:
      "Bantu grows up being constantly subjected to his father's scorn. However, he later learns that he was replaced from his real parents by his father, and decides to carve a place for himself within the family he truly belongs to.",
    popularity: 2.965,
    poster_path: "/sAjV06jQdAiAWw0dHkylAUy4bHL.jpg",
    release_date: "2023-02-10",
    title: "Shehzada",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
];

export const movieStub = {
  adult: false,
  backdrop_path: "/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg",
  belongs_to_collection: {
    id: 86311,
    name: "The Avengers Collection",
    poster_path: "/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg",
    backdrop_path: "/zuW6fOiusv4X9nnW3paHGfXcSll.jpg",
  },
  budget: 300000000,
  genres: [
    {
      id: 12,
      name: "Adventure",
    },
    {
      id: 28,
      name: "Action",
    },
    {
      id: 878,
      name: "Science Fiction",
    },
  ],
  homepage: "https://www.marvel.com/movies/avengers-infinity-war",
  id: 299536,
  imdb_id: "tt4154756",
  original_language: "en",
  original_title: "Avengers: Infinity War",
  overview:
    "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
  popularity: 213.909,
  poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
  production_companies: [
    {
      id: 420,
      logo_path: "/hUzeosd33nzE5MCNsZxCGEKTXaQ.png",
      name: "Marvel Studios",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2018-04-25",
  revenue: 2046239637,
  runtime: 149,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
    {
      english_name: "Xhosa",
      iso_639_1: "xh",
      name: "",
    },
  ],
  status: "Released",
  tagline: "An entire universe. Once and for all.",
  title: "Avengers: Infinity War",
  video: false,
  vote_average: 8.264,
  vote_count: 26159,
};
export const tvStub = {
  adult: false,
  backdrop_path: "/23WUgvjfnQFNwSPSSG9CdGFnauN.jpg",
  created_by: [
    {
      id: 56156,
      credit_id: "6160c3191d35630060c5c11d",
      name: "Bonnie Turner",
      gender: 1,
      profile_path: null,
    },
    {
      id: 56157,
      credit_id: "6160c3221d35630060c5c144",
      name: "Terry Turner",
      gender: 2,
      profile_path: null,
    },
    {
      id: 1212419,
      credit_id: "6160c3101d3563002bc093ae",
      name: "Gregg Mettler",
      gender: 0,
      profile_path: null,
    },
    {
      id: 3263710,
      credit_id: "6160c34067e0f70063082236",
      name: "Lindsay Turner",
      gender: 0,
      profile_path: null,
    },
  ],
  episode_run_time: [],
  first_air_date: "2023-01-19",
  genres: [
    {
      id: 35,
      name: "Comedy",
    },
  ],
  homepage: "https://www.netflix.com/title/81288370",
  id: 135959,
  in_production: true,
  languages: ["en"],
  last_air_date: "2023-01-19",
  last_episode_to_air: {
    air_date: "2023-01-19",
    episode_number: 10,
    id: 4115689,
    name: "Kids in America",
    overview:
      "As Sherri deals with her landlord, Leia’s last day in town gets complicated after Jay expresses doubts about a long-distance relationship.",
    production_code: "",
    runtime: 24,
    season_number: 1,
    show_id: 135959,
    still_path: "/zMuXHxK0ziC3MPJaJkQCz8jtj69.jpg",
    vote_average: 0.0,
    vote_count: 0,
  },
  name: "That '90s Show",
  next_episode_to_air: null,
  networks: [
    {
      id: 213,
      name: "Netflix",
      logo_path: "/wwemzKWzjKYJFfCeiB57q3r4Bcm.png",
      origin_country: "",
    },
  ],
  number_of_episodes: 10,
  number_of_seasons: 1,
  origin_country: ["US"],
  original_language: "en",
  original_name: "That '90s Show",
  overview:
    "Hello, Wisconsin! It's 1995 and Leia Forman, daughter of Eric and Donna, is visiting her grandparents for the summer where she bonds with a new generation of Point Place kids under the watchful eye of Kitty and the stern glare of Red. Sex, drugs and rock 'n roll never dies, it just changes clothes.",
  popularity: 76.84,
  poster_path: "/nZcufEuqZqNYMx6mNjlh2rmjDqx.jpg",
  production_companies: [
    {
      id: 3215,
      logo_path: "/yskyQQUMRlMHwkTs4DNdtIUcAjh.png",
      name: "Carsey-Werner Company",
      origin_country: "",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  seasons: [
    {
      air_date: "2023-01-19",
      episode_count: 10,
      id: 214873,
      name: "Season 1",
      overview: "",
      poster_path: "/nZcufEuqZqNYMx6mNjlh2rmjDqx.jpg",
      season_number: 1,
    },
  ],
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Returning Series",
  tagline: "Times change. Teenagers don’t.",
  type: "Scripted",
  vote_average: 7.045,
  vote_count: 44,
};
export const tvVideoStub = [
  {
    iso_639_1: "en",
    iso_3166_1: "US",
    name: "Series Trailer",
    key: "XZ8daibM3AE",
    published_at: "2013-03-25T16:28:54.000Z",
    site: "YouTube",
    size: 480,
    type: "Trailer",
    official: true,
    id: "5759db2fc3a3683e7c003df7",
  },
];
export const movieVideoStub = [
  {
    iso_639_1: "en",
    iso_3166_1: "US",
    name: "Footprints | Official Trailer | Indian Short Film",
    key: "TrwguVfuL9o",
    site: "YouTube",
    size: 1080,
    type: "Trailer",
    official: false,
    published_at: "2023-01-06T12:30:09.000Z",
    id: "63c597a7c9054f008999434c",
  },
];

export const discoverMovieStub = [
  {
    adult: false,
    backdrop_path: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    genre_ids: [16, 28, 12, 35, 10751, 14],
    id: 315162,
    original_language: "en",
    original_title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    popularity: 6201.733,
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    release_date: "2022-12-07",
    title: "Puss in Boots: The Last Wish",
    video: false,
    vote_average: 8.6,
    vote_count: 2587,
  },
  {
    adult: false,
    backdrop_path: "/q2fY4kMXKoGv4CQf310MCxpXlRI.jpg",
    genre_ids: [878, 27, 35],
    id: 536554,
    original_language: "en",
    original_title: "M3GAN",
    overview:
      "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
    popularity: 6064.293,
    poster_path: "/rxDPzExeovcBZY2IVWdYs87AzVE.jpg",
    release_date: "2022-12-28",
    title: "M3GAN",
    video: false,
    vote_average: 7.4,
    vote_count: 631,
  },
  {
    adult: false,
    backdrop_path: "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    popularity: 2478.474,
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    release_date: "2022-12-14",
    title: "Avatar: The Way of Water",
    video: false,
    vote_average: 7.7,
    vote_count: 4612,
  },
  {
    adult: false,
    backdrop_path: "/Aqldsq65Nj1KAkQD2MzkZsAk5N5.jpg",
    genre_ids: [28, 53, 18],
    id: 846433,
    original_language: "en",
    original_title: "The Enforcer",
    overview:
      "A noir thriller set in Miami, the film follows an enforcer who discovers his femme fatale boss has branched out into cyber sex trafficking, putting a young runaway he’s befriended at risk. He sacrifices everything to save the young girl from the deadly organization he’s spent his life building.",
    popularity: 2241.526,
    poster_path: "/72V1r1G8S87ELagVxjqAUdChMCt.jpg",
    release_date: "2022-09-22",
    title: "The Enforcer",
    video: false,
    vote_average: 7.1,
    vote_count: 81,
  },
  {
    adult: false,
    backdrop_path: "/5pMy5LF2JAleBNBtuzizfCMWM7k.jpg",
    genre_ids: [10752, 36, 18],
    id: 653851,
    original_language: "en",
    original_title: "Devotion",
    overview:
      "The harrowing true story of two elite US Navy fighter pilots during the Korean War. Their heroic sacrifices would ultimately make them the Navy's most celebrated wingmen.",
    popularity: 2044.18,
    poster_path: "/26yQPXymbWeCLKwcmyL8dRjAzth.jpg",
    release_date: "2022-11-23",
    title: "Devotion",
    video: false,
    vote_average: 7.3,
    vote_count: 120,
  },
  {
    adult: false,
    backdrop_path: "/sBOenwOZGRN5nZZGw4TxwtnfrEf.jpg",
    genre_ids: [28, 35, 80, 53],
    id: 899112,
    original_language: "en",
    original_title: "Violent Night",
    overview:
      "When a team of mercenaries breaks into a wealthy family compound on Christmas Eve, taking everyone inside hostage, the team isn’t prepared for a surprise combatant: Santa Claus is on the grounds, and he’s about to show why this Nick is no saint.",
    popularity: 1586.338,
    poster_path: "/1XSYOP0JjjyMz1irihvWywro82r.jpg",
    release_date: "2022-11-30",
    title: "Violent Night",
    video: false,
    vote_average: 7.7,
    vote_count: 1017,
  },
  {
    adult: false,
    backdrop_path: "/53BC9F2tpZnsGno2cLhzvGprDYS.jpg",
    genre_ids: [14, 28, 12, 53],
    id: 736526,
    original_language: "no",
    original_title: "Troll",
    overview:
      "Deep inside the mountain of Dovre, something gigantic awakens after being trapped for a thousand years. Destroying everything in its path, the creature is fast approaching the capital of Norway. But how do you stop something you thought only existed in Norwegian folklore?",
    popularity: 1519.719,
    poster_path: "/9z4jRr43JdtU66P0iy8h18OyLql.jpg",
    release_date: "2022-12-01",
    title: "Troll",
    video: false,
    vote_average: 6.7,
    vote_count: 1069,
  },
  {
    adult: false,
    backdrop_path: "/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
    genre_ids: [14, 28, 878],
    id: 436270,
    original_language: "en",
    original_title: "Black Adam",
    overview:
      "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
    popularity: 1303.947,
    poster_path: "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
    release_date: "2022-10-19",
    title: "Black Adam",
    video: false,
    vote_average: 7.2,
    vote_count: 3877,
  },
  {
    adult: false,
    backdrop_path: "/8I37NtDffNV7AZlDa7uDvvqhovU.jpg",
    genre_ids: [28, 12, 14, 878],
    id: 19995,
    original_language: "en",
    original_title: "Avatar",
    overview:
      "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
    popularity: 1231.261,
    poster_path: "/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
    release_date: "2009-12-15",
    title: "Avatar",
    video: false,
    vote_average: 7.6,
    vote_count: 28011,
  },
  {
    adult: false,
    backdrop_path: "/yYrvN5WFeGYjJnRzhY0QXuo4Isw.jpg",
    genre_ids: [28, 12, 878],
    id: 505642,
    original_language: "en",
    original_title: "Black Panther: Wakanda Forever",
    overview:
      "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
    popularity: 1216.323,
    poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    release_date: "2022-11-09",
    title: "Black Panther: Wakanda Forever",
    video: false,
    vote_average: 7.5,
    vote_count: 1694,
  },
  {
    adult: false,
    backdrop_path: "/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg",
    genre_ids: [35, 80, 9648],
    id: 661374,
    original_language: "en",
    original_title: "Glass Onion: A Knives Out Mystery",
    overview:
      "World-famous detective Benoit Blanc heads to Greece to peel back the layers of a mystery surrounding a tech billionaire and his eclectic crew of friends.",
    popularity: 1136.979,
    poster_path: "/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
    release_date: "2022-11-23",
    title: "Glass Onion: A Knives Out Mystery",
    video: false,
    vote_average: 7.1,
    vote_count: 2957,
  },
  {
    adult: false,
    backdrop_path: "/rodjjIJ8oh9nuBp86PhojcYHTEN.jpg",
    genre_ids: [28, 9648, 53, 80, 18],
    id: 740952,
    original_language: "en",
    original_title: "Savage Salvation",
    overview:
      "Newly engaged Shelby John and Ruby Red want a fresh start after their struggles with addiction, but when Shelby discovers his beloved Ruby dead on their porch, he embarks on a vengeful killing spree of the dealers who supplied her. Armed with nothing but adrenaline and a nail gun, Shelby begins to unleash chaos on the town’s criminal underbelly, as he hunt’s down crime lord Coyote. Sheriff Church must race against the clock to put an end to Shelby's vigilante justice before the entire town descends into a bloodbath.",
    popularity: 1211.338,
    poster_path: "/fJRt3mmZEvf8gQzoNLzjPtWpc9o.jpg",
    release_date: "2022-12-02",
    title: "Savage Salvation",
    video: false,
    vote_average: 6,
    vote_count: 51,
  },
  {
    adult: false,
    backdrop_path: "/tsjXBo4LmzV0Bb9hdrz25tzX5GD.jpg",
    genre_ids: [10402],
    id: 1041513,
    original_language: "en",
    original_title: "Encanto at the Hollywood Bowl",
    overview:
      "A taped performance of the Encanto Live-to-Film Concert Experience at the Hollywood Bowl. The original cast puts on a miracle of a concert as they sing the favorite songs, accompanied by a full orchestra and 50 person ensemble, and the Hollywood Bowl transforms into Casita!",
    popularity: 1054.789,
    poster_path: "/sa3Ku5yNVjp8NloWxJoI9dQjvOi.jpg",
    release_date: "2022-12-28",
    title: "Encanto at the Hollywood Bowl",
    video: false,
    vote_average: 7.1,
    vote_count: 38,
  },
  {
    adult: false,
    backdrop_path: "/gkseI3CUfQtMKX41XD4AxDzhQb7.jpg",
    genre_ids: [28, 18, 36],
    id: 724495,
    original_language: "en",
    original_title: "The Woman King",
    overview:
      "The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.",
    popularity: 1025.498,
    poster_path: "/438QXt1E3WJWb3PqNniK0tAE5c1.jpg",
    release_date: "2022-09-16",
    title: "The Woman King",
    video: false,
    vote_average: 7.9,
    vote_count: 1115,
  },
  {
    adult: false,
    backdrop_path: "/7GmQKKAB3q3xkpxt1VFt2DrfviW.jpg",
    genre_ids: [53, 80],
    id: 934287,
    original_language: "da",
    original_title: "Klienten",
    overview:
      "Renowned psychologist Susanne (Signe Egholm Olsen) is caught in a living nightmare when her new client (Anton Hjejle) turns out to be a wanted serial killer.",
    popularity: 978.23,
    poster_path: "/oUhZzMpHAMgdRgLbsvBIqhY7fKe.jpg",
    release_date: "2022-06-20",
    title: "The Last Client",
    video: false,
    vote_average: 7.8,
    vote_count: 37,
  },
  {
    adult: false,
    backdrop_path: "/ecaB1LUoQE1ylZJVF5KLRTkewt8.jpg",
    genre_ids: [28, 35, 80],
    id: 683328,
    original_language: "id",
    original_title: "The Big 4",
    overview:
      "A by-the-book female detective teams up with four down-on-their-luck assassins to investigate her father's murder.",
    popularity: 1047.888,
    poster_path: "/jrw684BhFJZ9Jac6KJda3hSQkxt.jpg",
    release_date: "2022-12-19",
    title: "The Big 4",
    video: false,
    vote_average: 7,
    vote_count: 94,
  },
  {
    adult: false,
    backdrop_path: "/nWs0auTqn2UaFGfTKtUE5tlTeBu.jpg",
    genre_ids: [10751, 35, 14],
    id: 668482,
    original_language: "en",
    original_title: "Roald Dahl's Matilda the Musical",
    overview:
      "An extraordinary young girl discovers her superpower and summons the remarkable courage, against all odds, to help others change their stories, whilst also taking charge of her own destiny. Standing up for what's right, she's met with miraculous results.",
    popularity: 987.424,
    poster_path: "/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg",
    release_date: "2022-11-25",
    title: "Roald Dahl's Matilda the Musical",
    video: false,
    vote_average: 6.8,
    vote_count: 406,
  },
  {
    adult: false,
    backdrop_path: "/94kQGMiFbs5MUTlt7kj9dewsMDi.jpg",
    genre_ids: [27, 53],
    id: 676547,
    original_language: "en",
    original_title: "Prey for the Devil",
    overview:
      "In response to a global rise in demonic possessions, the Catholic Church reopens exorcism schools to train priests in the Rite of Exorcism. On this spiritual battlefield, an unlikely warrior rises: a young nun, Sister Ann. Thrust onto the spiritual frontline with fellow student Father Dante, Sister Ann finds herself in a battle for the soul of a young girl and soon realizes the Devil has her right where he wants her.",
    popularity: 908.125,
    poster_path: "/iCvgemXf2Kpr2LvpDmt5J9NhjKM.jpg",
    release_date: "2022-10-23",
    title: "Prey for the Devil",
    video: false,
    vote_average: 7.2,
    vote_count: 424,
  },
  {
    adult: false,
    backdrop_path: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
    genre_ids: [12, 10751, 14],
    id: 411,
    original_language: "en",
    original_title:
      "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    overview:
      "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
    popularity: 1058.626,
    poster_path: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
    release_date: "2005-12-07",
    title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    video: false,
    vote_average: 7.1,
    vote_count: 9202,
  },
  {
    adult: false,
    backdrop_path: "/edOt2jNyCbb8SQSvulD2sRRJhmA.jpg",
    genre_ids: [28, 80, 53],
    id: 873126,
    original_language: "it",
    original_title: "Il mio nome è vendetta",
    overview:
      "After old enemies kill his family, a former mafia enforcer and his feisty daughter flee to Milan, where they hide out while plotting their revenge.",
    popularity: 834.324,
    poster_path: "/7l3war94J4tRyWUiLAGokr3ViF2.jpg",
    release_date: "2022-11-30",
    title: "My Name Is Vendetta",
    video: false,
    vote_average: 6.8,
    vote_count: 328,
  },
];

export const discoverTvStub = [
  {
    backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    first_air_date: "2023-01-15",
    genre_ids: [18, 10765, 10759],
    id: 100088,
    name: "The Last of Us",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    popularity: 7500.029,
    poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    vote_average: 8.9,
    vote_count: 912,
  },
  {
    backdrop_path: null,
    first_air_date: "2002-09-09",
    genre_ids: [],
    id: 20812,
    name: "Való Világ",
    origin_country: ["HU"],
    original_language: "hu",
    original_name: "Való Világ",
    overview: "",
    popularity: 2837.372,
    poster_path: "/kQ6EfC1igZRNSSsnQbLG2mrOLwj.jpg",
    vote_average: 0,
    vote_count: 0,
  },
  {
    backdrop_path: "/n9u72dPMB1e3IpgN3LHRaons6gw.jpg",
    first_air_date: "",
    genre_ids: [],
    id: 79855,
    name: "Questions pour un champion",
    origin_country: ["FR"],
    original_language: "fr",
    original_name: "Questions pour un champion",
    overview:
      "Samuel Etienne hosts this emblematic game, which sees four candidates compete each evening around questions of general culture.",
    popularity: 1998.21,
    poster_path: "/4vFsjMKcImBy1a49EkRakvMrgZw.jpg",
    vote_average: 2,
    vote_count: 1,
  },
  {
    backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    first_air_date: "2022-11-23",
    genre_ids: [10765, 9648, 35],
    id: 119051,
    name: "Wednesday",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    popularity: 1907.065,
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    vote_average: 8.7,
    vote_count: 5773,
  },
  {
    backdrop_path: "/qcpC9lv6VLL4Zw45EveYELyje1w.jpg",
    first_air_date: "2020-10-05",
    genre_ids: [18, 10766, 10751],
    id: 111453,
    name: "Gumm Hai Kisi Ke Pyaar Mein",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "घुम है किसिकी प्यार में",
    overview:
      "Virat sacrifices his love to honour the promise he made to a dying man. Trapped between the past and the present, will he find love beyond the chains of duty?",
    popularity: 1598.786,
    poster_path: "/uNjnoT3RChs2r7O9pDyx7TNBvIj.jpg",
    vote_average: 5.7,
    vote_count: 23,
  },
  {
    backdrop_path: "/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg",
    first_air_date: "2021-08-03",
    genre_ids: [10766],
    id: 130542,
    name: "Bhagya Lakshmi",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Bhagya Lakshmi",
    overview:
      "Hailing from a middle-class family, Lakshmi’s life is upended when she realises that her marriage to Rishi Oberoi, an industrialist’s son, is a sham to keep his death at bay.",
    popularity: 1586.009,
    poster_path: "/7wuKrFvbX7kAIF0ctotARsqayPo.jpg",
    vote_average: 5.1,
    vote_count: 13,
  },
  {
    backdrop_path: "/mNHRGO1gFpR2CYZdANe72kcKq7G.jpg",
    first_air_date: "2022-11-13",
    genre_ids: [80, 18],
    id: 153312,
    name: "Tulsa King",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Tulsa King",
    overview:
      "Just after he is released from prison after 25 years, New York mafia capo Dwight “The General” Manfredi is unceremoniously exiled by his boss to set up shop in Tulsa, Okla. Realizing that his mob family may not have his best interests in mind, Dwight slowly builds a “crew” from a group of unlikely characters, to help him establish a new criminal empire in a place that to him might as well be another planet.",
    popularity: 1495.468,
    poster_path: "/fwTv3RPRAIy0maOMns5eYRRwnDk.jpg",
    vote_average: 8.6,
    vote_count: 650,
  },
  {
    backdrop_path: "/1aQ0ETcIXFeC0uGcK7NvTg90zWi.jpg",
    first_air_date: "2022-08-22",
    genre_ids: [],
    id: 209326,
    name: "Rajjo",
    origin_country: ["IN"],
    original_language: "nl",
    original_name: "Rajjo",
    overview: "",
    popularity: 1436.953,
    poster_path: "/rdNwXdMDVDvjOlcXCPOR3m9t43r.jpg",
    vote_average: 5.3,
    vote_count: 4,
  },
  {
    backdrop_path: "/jLH03sLbkAGxrThdW6b2lrwwE4X.jpg",
    first_air_date: "2022-10-03",
    genre_ids: [18, 10751],
    id: 211239,
    name: "The Love in Your Eyes",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "내 눈에 콩깍지",
    overview:
      "Depicts the second love of a rogue daughter-in-law who appears in a 30-year-old gomtang restaurant, and a confident single mother Young Ih who says anything no matter what.\n\nJang Kyung Joon, who has the charm of a black-and-white man. Even though he shows the coolness of self-restraint from a large company that doesn't show his emotions easily, he shows both sides of being friendly in front of Lee Young Ih. Lee Young Ih, a single mother of steel mentality and a daughter-in-law with a bad attitude. She is sometimes angry, but she is a colorful charmer full of justice. Kim Hae Mi, her mother's daughter who has both her work and love in her hands, and Jang Kyung Joon's fiancée. It forms a tense rivalry with Bae Nouri. Jang Se Joon, the half-brother of Jang Kyung Joon, who has a friendly personality.",
    popularity: 1426.159,
    poster_path: "/gJnVJ3l4p1GDvGpwFedXhAJG3qE.jpg",
    vote_average: 5.7,
    vote_count: 3,
  },
  {
    backdrop_path: "/jANJGWIKavzyREXUMCHiXFzitDO.jpg",
    first_air_date: "2022-10-10",
    genre_ids: [10766, 18, 35],
    id: 204370,
    name: "Travessia",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Travessia",
    overview: "",
    popularity: 1415.348,
    poster_path: "/jFZJEoPzt2RKSsZG8QEWptX5Xyw.jpg",
    vote_average: 5.3,
    vote_count: 12,
  },
  {
    backdrop_path: "/5gGfJIMB2ynRzERryQo8hTcdQXi.jpg",
    first_air_date: "2022-10-10",
    genre_ids: [18, 9648, 10751],
    id: 211174,
    name: "Vengeance of the Bride",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "태풍의 신부",
    overview:
      "The story of a woman who becomes the daughter-in-law of an enemy for desperate revenge.",
    popularity: 1414.505,
    poster_path: "/aHUyK2XA76mn9GM36wu2rRKvwB5.jpg",
    vote_average: 2,
    vote_count: 1,
  },
  {
    backdrop_path: "/qtFJ4PMvc4qEqD0dLrpNaXIlhKC.jpg",
    first_air_date: "2022-09-05",
    genre_ids: [10764],
    id: 208711,
    name: "Een Jaar Van Je Leven",
    origin_country: ["NL"],
    original_language: "nl",
    original_name: "Een Jaar Van Je Leven",
    overview: "",
    popularity: 1413.652,
    poster_path: "/97obFkhpMLrZcQEUCI69v55etNL.jpg",
    vote_average: 4.8,
    vote_count: 6,
  },
  {
    backdrop_path: "/o5GsA1G5YEruuUNOYvWjlArIC37.jpg",
    first_air_date: "2022-09-19",
    genre_ids: [10766],
    id: 210506,
    name: "Sangue Oculto",
    origin_country: ["PT"],
    original_language: "pt",
    original_name: "Sangue Oculto",
    overview: "",
    popularity: 1404.18,
    poster_path: "/myCEG6C5Nk181jXzBek5MQEXpM2.jpg",
    vote_average: 4.6,
    vote_count: 7,
  },
  {
    backdrop_path: "/5NboRtvAKCU0KJGs5rXbw9deQf.jpg",
    first_air_date: "2021-10-27",
    genre_ids: [],
    id: 197109,
    name: "¿Cómo se llama esta relación?",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "¿Cómo se llama esta relación?",
    overview:
      "The new stage of Yeh Rishta Kya Kehlata Hai will deal with the rivalry between sisters set within the premise of a love triangle. It will basically revolve around the story of two sisters, Akshara and Aarohi, and how they get entangled in a relationship with their love interest, Abhimanyu.",
    popularity: 1401.962,
    poster_path: "/6ZfiG4P7jivJV0wgcNMSiS2Owhh.jpg",
    vote_average: 6.8,
    vote_count: 4,
  },
  {
    backdrop_path: "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
    first_air_date: "2022-11-02",
    genre_ids: [18],
    id: 213713,
    name: "Faltu",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Faltu",
    overview:
      "What's in a name? Amidst the arid landscape of Rajasthan, a young woman with dreamy eyes struggles to prove her worth.",
    popularity: 1400.868,
    poster_path: "/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg",
    vote_average: 4.3,
    vote_count: 6,
  },
  {
    backdrop_path: "/o8zk3QmHYMSC7UiJgFk81OFF1sc.jpg",
    first_air_date: "2022-08-22",
    genre_ids: [10766, 18],
    id: 204095,
    name: "Mar do Sertão",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Mar do Sertão",
    overview: "",
    popularity: 1340.748,
    poster_path: "/ixgnqO8xhFMb1zr8RRFsyeZ9CdD.jpg",
    vote_average: 4.3,
    vote_count: 21,
  },
  {
    backdrop_path: "/5s6BJd2vK5J2EQzGpX6OhHg9MM3.jpg",
    first_air_date: "2023-01-14",
    genre_ids: [80, 9648, 18],
    id: 210757,
    name: "The Knockout",
    origin_country: ["CN"],
    original_language: "zh",
    original_name: "狂飙",
    overview:
      "20 years of perseverance, hot-blooded teenagers finally become the people's hero.",
    popularity: 1195.13,
    poster_path: "/SIY6lVRZ9W1C4GU3Dvi3l4MSFs.jpg",
    vote_average: 8.8,
    vote_count: 8,
  },
  {
    backdrop_path: "/tghyYmdUyLRXwYAQveP7oDOYGqP.jpg",
    first_air_date: "1972-09-04",
    genre_ids: [],
    id: 2051,
    name: "The Price Is Right",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Price Is Right",
    overview:
      '"Come on down!" The Price Is Right features a wide variety of games and contests with the same basic challenge: Guess the prices of everyday (or not-quite-everyday) retail items. ',
    popularity: 1188.956,
    poster_path: "/6m4uYFAJwkanZXd0n0HUQ0lYHLl.jpg",
    vote_average: 6.2,
    vote_count: 59,
  },
  {
    backdrop_path: "/1LmJem0n7GgvefCZXQEPil3jquS.jpg",
    first_air_date: "2012-09-24",
    genre_ids: [18],
    id: 46881,
    name: "Corona de lágrimas",
    origin_country: ["MX"],
    original_language: "es",
    original_name: "Corona de lágrimas",
    overview:
      "Corona de Lágrimas is a 2012 Mexican telenovela produced by José Alberto Castro for Televisa. It is a remake of Corona de Lágrimas, produced in 1965 and starring Prudencia Grifell and Jorge Lavat.\n\nVictoria Ruffo, Africa Zavala and Mané de la Parra star as the protagonists, while Adriana Louvier, Ernesto Laguardia, Martha Julia and Alejandro Nones star as the antagonists.",
    popularity: 1078.949,
    poster_path: "/pSksCIGlXAIi58XMgFv3tUgTXDr.jpg",
    vote_average: 7.5,
    vote_count: 136,
  },
  {
    backdrop_path: "/2cvMMvo8VUfuQ40FYtIrqzoh7sG.jpg",
    first_air_date: "2013-04-15",
    genre_ids: [80, 18, 10766],
    id: 44953,
    name: "The Lord of the Skies",
    origin_country: ["MX"],
    original_language: "es",
    original_name: "El señor de los cielos",
    overview:
      "Set in the 1990s, these are the life and times of Amado Carrillo Fuentes, a man who became the head of the Juárez cartel. Nicknamed “El Señor de los Cielos” (Lord of the Skies) because of the large fleet of airplanes he used to transport drugs, he was also known for washing more than $200 million through Colombia to finance his huge fleet. He is described as the most powerful drug trafficker of his time.",
    popularity: 1077.221,
    poster_path: "/Ag7VUdnrRz5Qpq3Yn3E5OCvFnu0.jpg",
    vote_average: 7.8,
    vote_count: 2281,
  },
];
