export const logo = "/assets/logo.png";
export const backdrop = "/assets/pushpa_backdrop.png";
export const imageBaseUrl = "https://image.tmdb.org/t/p/";
// ids for genres used in api
export const genres = [
  {
    id: 28,
    name: "Action",
  },
  {
    id: 12,
    name: "Adventure",
  },
  {
    id: 16,
    name: "Animation",
  },
  {
    id: 35,
    name: "Comedy",
  },
  {
    id: 80,
    name: "Crime",
  },
  {
    id: 99,
    name: "Documentary",
  },
  {
    id: 18,
    name: "Drama",
  },
  {
    id: 10751,
    name: "Family",
  },
  {
    id: 14,
    name: "Fantasy",
  },
  {
    id: 36,
    name: "History",
  },
  {
    id: 27,
    name: "Horror",
  },
  {
    id: 10402,
    name: "Music",
  },
  {
    id: 9648,
    name: "Mystery",
  },
  {
    id: 10749,
    name: "Romance",
  },
  {
    id: 878,
    name: "Science Fiction",
  },
  {
    id: 10770,
    name: "TV Movie",
  },
  {
    id: 53,
    name: "Thriller",
  },
  {
    id: 10752,
    name: "War",
  },
  {
    id: 37,
    name: "Western",
  },
];
// ids for languages used in api
export const languages = [
  {
    iso_639_1: "an",
    english_name: "Aragonese",
    name: "",
  },
  {
    iso_639_1: "ak",
    english_name: "Akan",
    name: "",
  },
  {
    iso_639_1: "cr",
    english_name: "Cree",
    name: "",
  },
  {
    iso_639_1: "az",
    english_name: "Azerbaijani",
    name: "Azərbaycan",
  },
  {
    iso_639_1: "cs",
    english_name: "Czech",
    name: "Český",
  },
  {
    iso_639_1: "aa",
    english_name: "Afar",
    name: "",
  },
  {
    iso_639_1: "br",
    english_name: "Breton",
    name: "",
  },
  {
    iso_639_1: "af",
    english_name: "Afrikaans",
    name: "Afrikaans",
  },
  {
    iso_639_1: "bo",
    english_name: "Tibetan",
    name: "",
  },
  {
    iso_639_1: "ce",
    english_name: "Chechen",
    name: "",
  },
  {
    iso_639_1: "kw",
    english_name: "Cornish",
    name: "",
  },
  {
    iso_639_1: "fo",
    english_name: "Faroese",
    name: "",
  },
  {
    iso_639_1: "la",
    english_name: "Latin",
    name: "Latin",
  },
  {
    iso_639_1: "ng",
    english_name: "Ndonga",
    name: "",
  },
  {
    iso_639_1: "sc",
    english_name: "Sardinian",
    name: "",
  },
  {
    iso_639_1: "ti",
    english_name: "Tigrinya",
    name: "",
  },
  {
    iso_639_1: "tn",
    english_name: "Tswana",
    name: "",
  },
  {
    iso_639_1: "tr",
    english_name: "Turkish",
    name: "Türkçe",
  },
  {
    iso_639_1: "pa",
    english_name: "Punjabi",
    name: "ਪੰਜਾਬੀ",
  },
  {
    iso_639_1: "et",
    english_name: "Estonian",
    name: "Eesti",
  },
  {
    iso_639_1: "fr",
    english_name: "French",
    name: "Français",
  },
  {
    iso_639_1: "ha",
    english_name: "Hausa",
    name: "Hausa",
  },
  {
    iso_639_1: "is",
    english_name: "Icelandic",
    name: "Íslenska",
  },
  {
    iso_639_1: "li",
    english_name: "Limburgish",
    name: "",
  },
  {
    iso_639_1: "ln",
    english_name: "Lingala",
    name: "",
  },
  {
    iso_639_1: "ss",
    english_name: "Swati",
    name: "",
  },
  {
    iso_639_1: "ab",
    english_name: "Abkhazian",
    name: "",
  },
  {
    iso_639_1: "sh",
    english_name: "Serbo-Croatian",
    name: "",
  },
  {
    iso_639_1: "eu",
    english_name: "Basque",
    name: "euskera",
  },
  {
    iso_639_1: "fy",
    english_name: "Frisian",
    name: "",
  },
  {
    iso_639_1: "ja",
    english_name: "Japanese",
    name: "日本語",
  },
  {
    iso_639_1: "oj",
    english_name: "Ojibwa",
    name: "",
  },
  {
    iso_639_1: "or",
    english_name: "Oriya",
    name: "",
  },
  {
    iso_639_1: "pi",
    english_name: "Pali",
    name: "",
  },
  {
    iso_639_1: "su",
    english_name: "Sundanese",
    name: "",
  },
  {
    iso_639_1: "th",
    english_name: "Thai",
    name: "ภาษาไทย",
  },
  {
    iso_639_1: "ig",
    english_name: "Igbo",
    name: "",
  },
  {
    iso_639_1: "id",
    english_name: "Indonesian",
    name: "Bahasa indonesia",
  },
  {
    iso_639_1: "kk",
    english_name: "Kazakh",
    name: "қазақ",
  },
  {
    iso_639_1: "ki",
    english_name: "Kikuyu",
    name: "",
  },
  {
    iso_639_1: "ug",
    english_name: "Uighur",
    name: "",
  },
  {
    iso_639_1: "ve",
    english_name: "Venda",
    name: "",
  },
  {
    iso_639_1: "rw",
    english_name: "Kinyarwanda",
    name: "Kinyarwanda",
  },
  {
    iso_639_1: "mi",
    english_name: "Maori",
    name: "",
  },
  {
    iso_639_1: "nv",
    english_name: "Navajo",
    name: "",
  },
  {
    iso_639_1: "hi",
    english_name: "Hindi",
    name: "हिन्दी",
  },
  {
    iso_639_1: "pt",
    english_name: "Portuguese",
    name: "Português",
  },
  {
    iso_639_1: "sg",
    english_name: "Sango",
    name: "",
  },
  {
    iso_639_1: "sk",
    english_name: "Slovak",
    name: "Slovenčina",
  },
  {
    iso_639_1: "sr",
    english_name: "Serbian",
    name: "Srpski",
  },
  {
    iso_639_1: "ty",
    english_name: "Tahitian",
    name: "",
  },
  {
    iso_639_1: "xh",
    english_name: "Xhosa",
    name: "",
  },
  {
    iso_639_1: "ar",
    english_name: "Arabic",
    name: "العربية",
  },
  {
    iso_639_1: "co",
    english_name: "Corsican",
    name: "",
  },
  {
    iso_639_1: "bi",
    english_name: "Bislama",
    name: "",
  },
  {
    iso_639_1: "eo",
    english_name: "Esperanto",
    name: "Esperanto",
  },
  {
    iso_639_1: "hz",
    english_name: "Herero",
    name: "",
  },
  {
    iso_639_1: "fi",
    english_name: "Finnish",
    name: "suomi",
  },
  {
    iso_639_1: "iu",
    english_name: "Inuktitut",
    name: "",
  },
  {
    iso_639_1: "lv",
    english_name: "Latvian",
    name: "Latviešu",
  },
  {
    iso_639_1: "it",
    english_name: "Italian",
    name: "Italiano",
  },
  {
    iso_639_1: "nl",
    english_name: "Dutch",
    name: "Nederlands",
  },
  {
    iso_639_1: "kn",
    english_name: "Kannada",
    name: "?????",
  },
  {
    iso_639_1: "sa",
    english_name: "Sanskrit",
    name: "",
  },
  {
    iso_639_1: "sq",
    english_name: "Albanian",
    name: "shqip",
  },
  {
    iso_639_1: "tl",
    english_name: "Tagalog",
    name: "",
  },
  {
    iso_639_1: "lb",
    english_name: "Letzeburgesch",
    name: "",
  },
  {
    iso_639_1: "ts",
    english_name: "Tsonga",
    name: "",
  },
  {
    iso_639_1: "ml",
    english_name: "Malayalam",
    name: "",
  },
  {
    iso_639_1: "vo",
    english_name: "Volapük",
    name: "",
  },
  {
    iso_639_1: "zu",
    english_name: "Zulu",
    name: "isiZulu",
  },
  {
    iso_639_1: "os",
    english_name: "Ossetian; Ossetic",
    name: "",
  },
  {
    iso_639_1: "sm",
    english_name: "Samoan",
    name: "",
  },
  {
    iso_639_1: "za",
    english_name: "Zhuang",
    name: "",
  },
  {
    iso_639_1: "bn",
    english_name: "Bengali",
    name: "বাংলা",
  },
  {
    iso_639_1: "cu",
    english_name: "Slavic",
    name: "",
  },
  {
    iso_639_1: "ga",
    english_name: "Irish",
    name: "Gaeilge",
  },
  {
    iso_639_1: "gv",
    english_name: "Manx",
    name: "",
  },
  {
    iso_639_1: "hu",
    english_name: "Hungarian",
    name: "Magyar",
  },
  {
    iso_639_1: "jv",
    english_name: "Javanese",
    name: "",
  },
  {
    iso_639_1: "kr",
    english_name: "Kanuri",
    name: "",
  },
  {
    iso_639_1: "km",
    english_name: "Khmer",
    name: "",
  },
  {
    iso_639_1: "ky",
    english_name: "Kirghiz",
    name: "??????",
  },
  {
    iso_639_1: "na",
    english_name: "Nauru",
    name: "",
  },
  {
    iso_639_1: "nr",
    english_name: "Ndebele",
    name: "",
  },
  {
    iso_639_1: "oc",
    english_name: "Occitan",
    name: "",
  },
  {
    iso_639_1: "ro",
    english_name: "Romanian",
    name: "Română",
  },
  {
    iso_639_1: "ru",
    english_name: "Russian",
    name: "Pусский",
  },
  {
    iso_639_1: "hy",
    english_name: "Armenian",
    name: "",
  },
  {
    iso_639_1: "ch",
    english_name: "Chamorro",
    name: "Finu' Chamorro",
  },
  {
    iso_639_1: "xx",
    english_name: "No Language",
    name: "No Language",
  },
  {
    iso_639_1: "ba",
    english_name: "Bashkir",
    name: "",
  },
  {
    iso_639_1: "gl",
    english_name: "Galician",
    name: "Galego",
  },
  {
    iso_639_1: "io",
    english_name: "Ido",
    name: "",
  },
  {
    iso_639_1: "lu",
    english_name: "Luba-Katanga",
    name: "",
  },
  {
    iso_639_1: "mh",
    english_name: "Marshall",
    name: "",
  },
  {
    iso_639_1: "mg",
    english_name: "Malagasy",
    name: "",
  },
  {
    iso_639_1: "mo",
    english_name: "Moldavian",
    name: "",
  },
  {
    iso_639_1: "mn",
    english_name: "Mongolian",
    name: "",
  },
  {
    iso_639_1: "nd",
    english_name: "Ndebele",
    name: "",
  },
  {
    iso_639_1: "no",
    english_name: "Norwegian",
    name: "Norsk",
  },
  {
    iso_639_1: "pl",
    english_name: "Polish",
    name: "Polski",
  },
  {
    iso_639_1: "sw",
    english_name: "Swahili",
    name: "Kiswahili",
  },
  {
    iso_639_1: "tg",
    english_name: "Tajik",
    name: "",
  },
  {
    iso_639_1: "to",
    english_name: "Tonga",
    name: "",
  },
  {
    iso_639_1: "wa",
    english_name: "Walloon",
    name: "",
  },
  {
    iso_639_1: "yi",
    english_name: "Yiddish",
    name: "",
  },
  {
    iso_639_1: "en",
    english_name: "English",
    name: "English",
  },
  {
    iso_639_1: "as",
    english_name: "Assamese",
    name: "",
  },
  {
    iso_639_1: "gd",
    english_name: "Gaelic",
    name: "",
  },
  {
    iso_639_1: "kl",
    english_name: "Kalaallisut",
    name: "",
  },
  {
    iso_639_1: "my",
    english_name: "Burmese",
    name: "",
  },
  {
    iso_639_1: "qu",
    english_name: "Quechua",
    name: "",
  },
  {
    iso_639_1: "sn",
    english_name: "Shona",
    name: "",
  },
  {
    iso_639_1: "uk",
    english_name: "Ukrainian",
    name: "Український",
  },
  {
    iso_639_1: "fa",
    english_name: "Persian",
    name: "فارسی",
  },
  {
    iso_639_1: "ka",
    english_name: "Georgian",
    name: "ქართული",
  },
  {
    iso_639_1: "gu",
    english_name: "Gujarati",
    name: "",
  },
  {
    iso_639_1: "av",
    english_name: "Avaric",
    name: "",
  },
  {
    iso_639_1: "ae",
    english_name: "Avestan",
    name: "",
  },
  {
    iso_639_1: "gn",
    english_name: "Guarani",
    name: "",
  },
  {
    iso_639_1: "mt",
    english_name: "Maltese",
    name: "Malti",
  },
  {
    iso_639_1: "ne",
    english_name: "Nepali",
    name: "",
  },
  {
    iso_639_1: "sv",
    english_name: "Swedish",
    name: "svenska",
  },
  {
    iso_639_1: "tt",
    english_name: "Tatar",
    name: "",
  },
  {
    iso_639_1: "wo",
    english_name: "Wolof",
    name: "Wolof",
  },
  {
    iso_639_1: "cn",
    english_name: "Cantonese",
    name: "广州话 / 廣州話",
  },
  {
    iso_639_1: "cv",
    english_name: "Chuvash",
    name: "",
  },
  {
    iso_639_1: "da",
    english_name: "Danish",
    name: "Dansk",
  },
  {
    iso_639_1: "dz",
    english_name: "Dzongkha",
    name: "",
  },
  {
    iso_639_1: "ny",
    english_name: "Chichewa; Nyanja",
    name: "",
  },
  {
    iso_639_1: "rn",
    english_name: "Rundi",
    name: "Kirundi",
  },
  {
    iso_639_1: "st",
    english_name: "Sotho",
    name: "",
  },
  {
    iso_639_1: "tk",
    english_name: "Turkmen",
    name: "",
  },
  {
    iso_639_1: "uz",
    english_name: "Uzbek",
    name: "ozbek",
  },
  {
    iso_639_1: "vi",
    english_name: "Vietnamese",
    name: "Tiếng Việt",
  },
  {
    iso_639_1: "el",
    english_name: "Greek",
    name: "ελληνικά",
  },
  {
    iso_639_1: "ca",
    english_name: "Catalan",
    name: "Català",
  },
  {
    iso_639_1: "cy",
    english_name: "Welsh",
    name: "Cymraeg",
  },
  {
    iso_639_1: "de",
    english_name: "German",
    name: "Deutsch",
  },
  {
    iso_639_1: "ks",
    english_name: "Kashmiri",
    name: "",
  },
  {
    iso_639_1: "ms",
    english_name: "Malay",
    name: "Bahasa melayu",
  },
  {
    iso_639_1: "nb",
    english_name: "Norwegian Bokmål",
    name: "Bokmål",
  },
  {
    iso_639_1: "rm",
    english_name: "Raeto-Romance",
    name: "",
  },
  {
    iso_639_1: "si",
    english_name: "Sinhalese",
    name: "සිංහල",
  },
  {
    iso_639_1: "es",
    english_name: "Spanish",
    name: "Español",
  },
  {
    iso_639_1: "te",
    english_name: "Telugu",
    name: "తెలుగు",
  },
  {
    iso_639_1: "tw",
    english_name: "Twi",
    name: "",
  },
  {
    iso_639_1: "ps",
    english_name: "Pushto",
    name: "پښتو",
  },
  {
    iso_639_1: "bg",
    english_name: "Bulgarian",
    name: "български език",
  },
  {
    iso_639_1: "mk",
    english_name: "Macedonian",
    name: "",
  },
  {
    iso_639_1: "ik",
    english_name: "Inupiaq",
    name: "",
  },
  {
    iso_639_1: "ko",
    english_name: "Korean",
    name: "한국어/조선말",
  },
  {
    iso_639_1: "lt",
    english_name: "Lithuanian",
    name: "Lietuvių",
  },
  {
    iso_639_1: "om",
    english_name: "Oromo",
    name: "",
  },
  {
    iso_639_1: "se",
    english_name: "Northern Sami",
    name: "",
  },
  {
    iso_639_1: "so",
    english_name: "Somali",
    name: "Somali",
  },
  {
    iso_639_1: "ta",
    english_name: "Tamil",
    name: "தமிழ்",
  },
  {
    iso_639_1: "ur",
    english_name: "Urdu",
    name: "اردو",
  },
  {
    iso_639_1: "am",
    english_name: "Amharic",
    name: "",
  },
  {
    iso_639_1: "bs",
    english_name: "Bosnian",
    name: "Bosanski",
  },
  {
    iso_639_1: "dv",
    english_name: "Divehi",
    name: "",
  },
  {
    iso_639_1: "ay",
    english_name: "Aymara",
    name: "",
  },
  {
    iso_639_1: "bm",
    english_name: "Bambara",
    name: "Bamanankan",
  },
  {
    iso_639_1: "ii",
    english_name: "Yi",
    name: "",
  },
  {
    iso_639_1: "ie",
    english_name: "Interlingue",
    name: "",
  },
  {
    iso_639_1: "kv",
    english_name: "Komi",
    name: "",
  },
  {
    iso_639_1: "ku",
    english_name: "Kurdish",
    name: "",
  },
  {
    iso_639_1: "nn",
    english_name: "Norwegian Nynorsk",
    name: "",
  },
  {
    iso_639_1: "zh",
    english_name: "Mandarin",
    name: "普通话",
  },
  {
    iso_639_1: "he",
    english_name: "Hebrew",
    name: "עִבְרִית",
  },
  {
    iso_639_1: "ee",
    english_name: "Ewe",
    name: "Èʋegbe",
  },
  {
    iso_639_1: "fj",
    english_name: "Fijian",
    name: "",
  },
  {
    iso_639_1: "ff",
    english_name: "Fulah",
    name: "Fulfulde",
  },
  {
    iso_639_1: "ht",
    english_name: "Haitian; Haitian Creole",
    name: "",
  },
  {
    iso_639_1: "hr",
    english_name: "Croatian",
    name: "Hrvatski",
  },
  {
    iso_639_1: "ia",
    english_name: "Interlingua",
    name: "",
  },
  {
    iso_639_1: "kj",
    english_name: "Kuanyama",
    name: "",
  },
  {
    iso_639_1: "lo",
    english_name: "Lao",
    name: "",
  },
  {
    iso_639_1: "lg",
    english_name: "Ganda",
    name: "",
  },
  {
    iso_639_1: "mr",
    english_name: "Marathi",
    name: "",
  },
  {
    iso_639_1: "sd",
    english_name: "Sindhi",
    name: "",
  },
  {
    iso_639_1: "be",
    english_name: "Belarusian",
    name: "беларуская мова",
  },
  {
    iso_639_1: "ho",
    english_name: "Hiri Motu",
    name: "",
  },
  {
    iso_639_1: "kg",
    english_name: "Kongo",
    name: "",
  },
  {
    iso_639_1: "sl",
    english_name: "Slovenian",
    name: "Slovenščina",
  },
  {
    iso_639_1: "yo",
    english_name: "Yoruba",
    name: "Èdè Yorùbá",
  },
];
// DUMMY DATA
export const upcomingMovies = [
  {
    adult: false,
    backdrop_path: "/sJN04jAqCgiZ5mWjzD5WX49ncca.jpg",
    genre_ids: [28, 18, 53],
    id: 864692,
    original_language: "hi",
    original_title: "पठान",
    overview:
      "A soldier caught by enemies and presumed dead comes back to complete his mission, accompanied by old companions and foes.",
    popularity: 29.098,
    poster_path: "/m1b9toKYyCujHuLoXB5GSDunO9e.jpg",
    release_date: "2023-01-25",
    title: "Pathaan",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/6nS2PhKIsOkcVMZroH2diX3U27l.jpg",
    genre_ids: [53],
    id: 872028,
    original_language: "ml",
    original_title: "Alone",
    overview: "",
    popularity: 9.834,
    poster_path: "/1YoSk9SH4zW1piVORvHp0VLs4MM.jpg",
    release_date: "2023-01-26",
    title: "Alone",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/eBa978z4R19VXT1JSB9g5kk8T4k.jpg",
    genre_ids: [28, 53],
    id: 938890,
    original_language: "te",
    original_title: "Hunt",
    overview: "",
    popularity: 9.241,
    poster_path: "/6QnfT7zunSxKwbQmmT9FoxccwZe.jpg",
    release_date: "2023-01-26",
    title: "Hunt",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/glHgUMsme2couS42hBoPfvhwArC.jpg",
    genre_ids: [],
    id: 859664,
    original_language: "bn",
    original_title: "Footprints",
    overview:
      "A morning in the life of a house help comes crashing down on her as she navigates various odds at her home and at the place where she works.",
    popularity: 10.543,
    poster_path: "/zgTxHRXDbF6M0j7fjMR50On4nj7.jpg",
    release_date: "2023-01-22",
    title: "Footprints",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 1067209,
    original_language: "en",
    original_title: "Gandhi Godse Ek Yudh",
    overview:
      "The video depicts the war of ideologies between Mahatma Gandhi and Nathuram Godse, increasing the curiosity level amongst the viewers to watch the film.",
    popularity: 9.756,
    poster_path: "/7MKuFlrrLJtiV49sxL4P640KP6M.jpg",
    release_date: "2023-01-26",
    title: "Gandhi Godse Ek Yudh",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [28, 53],
    id: 942058,
    original_language: "hi",
    original_title: "Tehran",
    overview: "Upcoming hindi action-thriller",
    popularity: 9.422,
    poster_path: "/wM1kwZfiulxeBUCdeFoblNLTcgM.jpg",
    release_date: "2023-01-26",
    title: "Tehran",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 881935,
    original_language: "bn",
    original_title: "Doctor Bakshi",
    overview:
      "After serving a jail sentence, Doctor Bakshi resumes his methods of seeking justice.",
    popularity: 8.15,
    poster_path: "/vUvybeq2TZthXD6w8oRDwJ0sWln.jpg",
    release_date: "2023-01-27",
    title: "Doctor Bakshi",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/uonWHNSayYsAJTKAmFzZV2EYkq1.jpg",
    genre_ids: [18, 80],
    id: 797186,
    original_language: "ml",
    original_title: "തങ്കം",
    overview: "",
    popularity: 9.058,
    poster_path: "/lB4VhlVcJGxBTHtSgFaCJdFrmxL.jpg",
    release_date: "2023-01-26",
    title: "Thankam",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/buamYrukfn58GdKHF3kF7U2F0dq.jpg",
    genre_ids: [18, 10749],
    id: 1045394,
    original_language: "te",
    original_title: "బుట్టబొమ్మ",
    overview:
      "A young woman falls in love with a man after dialing his number by mistake. However, when she visits his city to meet him, another stranger enters her life.",
    popularity: 8.561,
    poster_path: "/7BkOzXTTwSO11AMTp9dO3tuLXOd.jpg",
    release_date: "2023-01-26",
    title: "Butta Bomma",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18],
    id: 1039062,
    original_language: "as",
    original_title: "Anur",
    overview: "",
    popularity: 6.185,
    poster_path: "/4bawk6pnHU6Ghn1OoDd7rape7aM.jpg",
    release_date: "2023-01-27",
    title: "Eyes on the Sunshine",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/vRqpsbtyoawRgo0hGVBbcfLXymB.jpg",
    genre_ids: [10749, 18, 10402],
    id: 1049623,
    original_language: "hi",
    original_title: "Almost Pyaar with DJ Mohabbat",
    overview:
      "In London, a girl likes a boy a little too much. And, in a parallel universe, there's a boy who likes a girl. These two unrequited love stories, burdened by social status, caste, religion and inequality are breathlessly headed towards each other...two tragic love stories, one musical and an uncanny coincidence as told by the Guru of Love: DJ Mohabbat.",
    popularity: 3.47,
    poster_path: "/5OKVJdLBFB2EOjCNpZlnu09HVL1.jpg",
    release_date: "2023-02-03",
    title: "Almost Pyaar with DJ Mohabbat",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/489kR2a6iZFx25FtRdpvVMPHaLv.jpg",
    genre_ids: [28, 53],
    id: 1019638,
    original_language: "hi",
    original_title: "Faraaz",
    overview:
      "Based on the real-life terrorist attack that ravaged a Dhaka cafe, Faraaz is a tense hostage drama that unspools over one claustrophobic night.",
    popularity: 4.899,
    poster_path: "/5Dn3X97sTB15sBIdX8gkkhqCOyD.jpg",
    release_date: "2023-02-03",
    title: "Faraaz",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/4aT9KMfA8Q5aKgL8LAu5PIcU3OF.jpg",
    genre_ids: [10751],
    id: 1075867,
    original_language: "ta",
    original_title: "Meippada Sei",
    overview:
      "Four ignorant boys were surviving their life with the support of parents in Tanjore village, one of them (Muthupandi) falling in love, thereby, opposition occurring, cause of lower & upper casting and racism, then how he got marry with his girlfriend moreover, to escaping from their parents, the couple has decided to moved towards Chennai along with friends of muthupandi, After arrival at Chennai before start-up of their life over there, unfortunately, they found the injured hand of the someone’s body in dead condition at the back side of their residence, scared and reported to the nearby police station, accordingly, they got assaulted by concerned local gangster. The Meippada Sei Climax would be illustrated: Whether the criminal has been punished by Indian law? Or Ignorant / village people? And how are they rejoining their families? The movie will be a family entertainer and contains the 4 fights & 4 songs, moreover with the message of sexual harassment/ abuse for society.",
    popularity: 5.379,
    poster_path: "/9QqfW5GQEx89MhbQcd8uWK88rp3.jpg",
    release_date: "2023-01-27",
    title: "Meippada Sei",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/xvjSATJp8xS1EKkmqWPTfU6KD9B.jpg",
    genre_ids: [],
    id: 945167,
    original_language: "ml",
    original_title: "ഇരട്ട",
    overview: "",
    popularity: 4.33,
    poster_path: "/ittBLkDQ0e605gHBpl73sFmRsmd.jpg",
    release_date: "2023-02-03",
    title: "Iratta",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/k4XRBh9WbNEStWs35Y3Egv29e0A.jpg",
    genre_ids: [35, 27],
    id: 976121,
    original_language: "ml",
    original_title: "രോമാഞ്ചം",
    overview:
      "Romancham is a story based on real incidents that happened in the life of 7 bachelors in Bangalore in 2007 after playing the Ouija board and events followed by it.",
    popularity: 3.533,
    poster_path: "/kQ4xbvyo5b2xjyvpIoLqTpVPP5J.jpg",
    release_date: "2023-02-03",
    title: "Romancham",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 953120,
    original_language: "ml",
    original_title: "ബൂമറാംഗ്",
    overview: "",
    popularity: 3.458,
    poster_path: "/ewg6pD4ov1Kz1Yi8oAP8svNVYMQ.jpg",
    release_date: "2023-02-03",
    title: "Boomerang",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/A8K7IIPiQykcZ3iNr4iE3oJNLc7.jpg",
    genre_ids: [28, 18],
    id: 866198,
    original_language: "ta",
    original_title: "மைக்கேல்",
    overview: "",
    popularity: 3.443,
    poster_path: "/1HChuuIpOungXAtotqVfhCBZUBK.jpg",
    release_date: "2023-02-03",
    title: "Michael",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 981372,
    original_language: "ml",
    original_title: "വെടിക്കെട്ടു",
    overview: "",
    popularity: 3.825,
    poster_path: null,
    release_date: "2023-02-03",
    title: "Vedikettu",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 881420,
    original_language: "ml",
    original_title: "Momo in Dubai",
    overview: "",
    popularity: 3.431,
    poster_path: "/uaj6jwRt7dowCLh2u1A4jbuwVEZ.jpg",
    release_date: "2023-02-03",
    title: "Momo in Dubai",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/7fIRDNUxrn6ulDXYWEgzmw0O9JB.jpg",
    genre_ids: [28, 35, 18, 10749],
    id: 884434,
    original_language: "hi",
    original_title: "Shehzada",
    overview:
      "Bantu grows up being constantly subjected to his father's scorn. However, he later learns that he was replaced from his real parents by his father, and decides to carve a place for himself within the family he truly belongs to.",
    popularity: 2.965,
    poster_path: "/sAjV06jQdAiAWw0dHkylAUy4bHL.jpg",
    release_date: "2023-02-10",
    title: "Shehzada",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
];
